let catalog; let zh=false;
const $=s=>document.querySelector(s);
const text=(en,cn)=>zh?cn:en;
const moduleByKey=k=>catalog.modules.find(m=>m.key===k);
const app=()=>$('#app');
const defaultApiBase=location.hostname==='127.0.0.1'||location.hostname==='localhost'?'http://127.0.0.1:8900':'https://unlimited-reported-reviewer-fish.trycloudflare.com';
const getApiBase=()=>localStorage.getItem('cropdrought_api_base')||defaultApiBase;
const setApiBase=v=>localStorage.setItem('cropdrought_api_base',v.replace(/\/+$/,''));

function home(){
  const featured=catalog.modules.slice(0,6).map(moduleCard).join('');
  return `<section class="hero"><div><div class="eyebrow">Comparative plant single-cell resource</div><h1>From cell atlases<br>to drought virtual cells.</h1><p>${text('A curated multi-species single-cell resource connecting cell identity, developmental dynamics, regulatory programs and drought-related inference.','面向抗旱虚拟细胞研究的多物种单细胞资源，连接细胞身份、发育动态、调控程序与抗旱推断。')}</p><div class="actions"><a class="button" href="#/species">${text('Explore species','浏览物种')}</a><a class="button secondary" href="#/analyses">${text('View analyses','查看分析')}</a></div></div><aside class="hero-card"><h3>${text('Current release','当前版本')}</h3><ul><li>21 plant species</li><li>9 analysis modules</li><li>188 available result panels</li><li>Curated QC and provenance</li></ul></aside></section>
  <section class="stats"><div class="stat"><strong>${catalog.stats.species}</strong><span>${text('Plant species','植物物种')}</span></div><div class="stat"><strong>${catalog.stats.modules}</strong><span>${text('Analysis modules','分析模块')}</span></div><div class="stat"><strong>${catalog.stats.available}</strong><span>${text('Available panels','有效面板')}</span></div><div class="stat"><strong>1</strong><span>${text('Known missing result','已知缺失结果')}</span></div></section>
  <section class="section"><div class="section-head"><h2>${text('Analysis landscape','分析概览')}</h2><p>${text('Standardized views across all species. Open a module to inspect the complete supplementary sheet or download the publication PDF.','统一展示所有物种结果，可查看完整附录大图或下载论文 PDF。')}</p></div><div class="grid">${featured}</div></section>`;
}
function moduleCard(m){return `<article class="card"><a href="#/analysis/${m.key}"><img loading="lazy" src="${m.preview}" alt="${m.name}"></a><div class="card-body"><h3>${zh?m.name_zh:m.name}</h3><p>${m.description}</p><div class="meta"><span class="tag">${m.present}/${m.expected} panels</span>${m.missing.length?`<span class="tag warn">Missing: ${m.missing.join(', ')}</span>`:''}</div></div></article>`}
function analyses(){return `<section class="section"><div class="section-head"><h1>${text('Analysis modules','分析模块')}</h1><p>${text('Nine complementary views of the current plant single-cell collection.','当前植物单细胞数据集的九类互补分析结果。')}</p></div><div class="grid">${catalog.modules.map(moduleCard).join('')}</div></section>`}
function species(){return `<section class="section"><div class="section-head"><h1>${text('Species collection','物种集合')}</h1><p>${text('Browse standardized results for each of the 21 plant species.','浏览 21 个植物物种的标准化分析结果。')}</p></div><input id="speciesSearch" class="search" placeholder="${text('Search species, Latin name or family…','搜索物种、拉丁名或科名…')}"><div id="speciesGrid" class="grid">${speciesCards(catalog.species)}</div></section>`}
function speciesCards(items){return items.map(s=>`<a class="card species-card" href="#/species/${s.slug}"><div class="eyebrow">${s.family}</div><h3>${s.name}</h3><em>${s.latin}</em><div class="meta"><span class="tag">${s.panels.filter(p=>p.status==='present').length}/${catalog.modules.length} modules</span></div></a>`).join('')}
function speciesDetail(slug){const s=catalog.species.find(x=>x.slug===slug);if(!s)return notFound();return `<section class="detail-hero"><div class="eyebrow">${s.family}</div><h1>${s.name}</h1><em>${s.latin}</em></section><section class="section"><div class="panel-grid">${s.panels.map(p=>{const m=moduleByKey(p.module);return `<article class="panel">${p.image?`<img loading="lazy" src="${p.image}" alt="${s.name} ${m.name}">`:`<div class="missing"><b>${text('Result unavailable','结果缺失')}</b><br>${text('Insufficient mapped cell-cycle markers','映射到的细胞周期标记不足')}</div>`}<h3>${zh?m.name_zh:m.name}</h3></article>`}).join('')}</div></section>`}
function analysisDetail(key){const m=moduleByKey(key);if(!m)return notFound();return `<section class="detail-hero"><div class="eyebrow">Analysis module</div><h1>${zh?m.name_zh:m.name}</h1><p>${m.description}</p></section><section class="section"><div class="panel"><img class="sheet" src="${m.preview}" alt="${m.name} all species"><div class="meta"><span class="tag">${m.present}/${m.expected} panels</span>${m.missing.length?`<span class="tag warn">Missing: ${m.missing.join(', ')}</span>`:''}</div><p><a class="button" href="${m.pdf}" download>${text('Download publication PDF','下载论文 PDF')}</a></p></div></section>`}
function downloads(){return `<section class="section"><div class="section-head"><h1>${text('Downloads','结果下载')}</h1><p>${text('Publication sheets and transparent provenance records. Large raw matrices are not exposed in this MVP.','提供论文附录图和来源记录；当前版本不公开大型原始矩阵。')}</p></div><div class="download-list">${catalog.modules.map(m=>`<div class="download-row"><div><b>${zh?m.name_zh:m.name}</b><br><small>${m.present}/${m.expected} panels</small></div><a href="${m.pdf}" download>PDF ↓</a></div>`).join('')}<div class="download-row"><b>Panel manifest</b><a href="assets/downloads/panel_manifest.tsv" download>TSV ↓</a></div><div class="download-row"><b>QC summary</b><a href="assets/downloads/qc_summary.tsv" download>TSV ↓</a></div><div class="download-row"><b>Figure captions</b><a href="assets/downloads/figure_captions.md" download>MD ↓</a></div></div></section>`}
function predictor(){const speciesOpts=catalog.species.map(s=>`<option value="${s.slug}">${s.name} (${s.slug})</option>`).join('');return `<section class="detail-hero"><div class="eyebrow">Interactive tool</div><h1>Virtual Cell Predictor</h1><p>${text('Submit a perturbation request to the server-side model API. The current backend is a replaceable MVP interface and can be connected to the trained model later.','向服务器端模型 API 提交基因扰动预测请求。当前后端是可替换的 MVP 接口，后续可接入真实训练模型。')}</p></section><section class="section predictor-layout"><form id="predictForm" class="predictor-form"><h2>${text('Prediction input','预测输入')}</h2><label>API Base URL<input name="apiBase" value="${getApiBase()}" placeholder="https://your-api.example.com"></label><div class="notice compact">${text('GitHub Pages uses HTTPS. For public use, the API also needs HTTPS; local testing can use http://127.0.0.1:8900.','GitHub Pages 是 HTTPS；公开使用时 API 也需要 HTTPS。本地测试可用 http://127.0.0.1:8900。')}</div><label>${text('Species','物种')}<select name="species">${speciesOpts}</select></label><label>${text('Cell type','细胞类型')}<input name="cell_type" value="guard cell" required></label><label>${text('Gene ID','基因 ID')}<input name="gene_id" value="Glyma.01G000100" required></label><label>${text('Perturbation','扰动方式')}<select name="perturbation"><option value="knockdown">knockdown</option><option value="overexpression">overexpression</option></select></label><label>${text('Strength','扰动强度')}<input name="strength" type="number" min="0" max="10" step="0.1" value="0.5" required></label><label>${text('Condition','条件')}<select name="condition"><option value="drought">drought</option><option value="control">control</option></select></label><button class="button" type="submit">${text('Run prediction','提交预测')}</button></form><div class="predictor-result"><h2>${text('Result','结果')}</h2><div id="predictStatus" class="result-box">${text('Submit a job to see model output here.','提交任务后将在这里显示模型输出。')}</div></div></section>`}
function methods(){return `<section class="section"><div class="prose"><div class="eyebrow">Methods & scope</div><h1>${text('About this release','关于当前版本')}</h1><p>${text('This portal presents curated outputs from a comparative plant single-cell transcriptomics workflow. It is the first data-facing layer of a future drought virtual-cell platform.','本门户展示植物跨物种单细胞转录组流程的整理结果，是未来抗旱虚拟细胞平台的数据展示层。')}</p><h2>${text('Current scope','当前范围')}</h2><p>${text('The MVP contains cell atlases, clustering, cell composition, pseudotime, RNA velocity, cell communication, SCENIC regulons, cell-cycle states and bulk–single-cell deconvolution across 21 species.','MVP 包含 21 个物种的细胞图谱、聚类、组成、拟时序、RNA velocity、细胞通讯、SCENIC、细胞周期和反卷积结果。')}</p><div class="notice"><b>${text('Known limitation:','已知限制：')}</b> ${text('Tobacco cell-cycle inference is unavailable because only two G2/M marker genes mapped successfully.','烟草细胞周期分析因仅映射到 2 个 G2/M 标记基因而未完成。')}</div><h2>${text('Data policy','数据策略')}</h2><p>${text('This local preview exposes only selected figures, publication PDFs and provenance tables. FASTQ, h5ad, loom and model artifacts remain private until licensing, citation and release rules are finalized.','本地预览仅展示筛选图片、论文 PDF 和来源表；FASTQ、h5ad、loom 与模型文件在授权、引用和发布规则确定前保持私有。')}</p></div></section>`}
function notFound(){return `<section class="section"><h1>Not found</h1><a href="#/home">Return home</a></section>`}
function resultHtml(result){const p=result.prediction;return `<div class="score-card"><strong>${p.drought_resistance_score}</strong><span>${text('Drought resistance score','抗旱评分')}</span></div><div class="meta"><span class="tag">baseline ${p.baseline_score}</span><span class="tag">delta ${p.delta}</span><span class="tag">confidence ${p.confidence}</span><span class="tag">${p.cell_state_shift}</span></div><h3>${text('Top affected genes','影响最大的基因')}</h3><table class="mini-table"><thead><tr><th>Rank</th><th>Gene</th><th>log2FC</th><th>Impact</th></tr></thead><tbody>${result.top_genes.map(g=>`<tr><td>${g.rank}</td><td>${g.gene_id}</td><td>${g.predicted_log2fc}</td><td>${g.impact_score}</td></tr>`).join('')}</tbody></table><h3>${text('Top regulators','主要调控因子')}</h3><table class="mini-table"><thead><tr><th>Rank</th><th>TF</th><th>Impact</th></tr></thead><tbody>${result.top_tfs.map(t=>`<tr><td>${t.rank}</td><td>${t.tf}</td><td>${t.regulatory_impact}</td></tr>`).join('')}</tbody></table><p class="muted">${result.note||''}</p>`}
async function pollJob(apiBase,jobId){const box=$('#predictStatus');for(let i=0;i<120;i++){const r=await fetch(`${apiBase}/api/jobs/${jobId}`);const job=await r.json();box.innerHTML=`${text('Job status','任务状态')}: <b>${job.status}</b><br><small>${jobId}</small>`;if(job.status==='completed'){const rr=await fetch(`${apiBase}/api/jobs/${jobId}/result`);const result=await rr.json();box.innerHTML=resultHtml(result);return}if(job.status==='failed')throw new Error(job.error||'job failed');await new Promise(resolve=>setTimeout(resolve,1500))}throw new Error('timeout waiting for job')}
function bindPredictor(){const form=$('#predictForm');if(!form)return;form.addEventListener('submit',async e=>{e.preventDefault();const box=$('#predictStatus');try{const fd=new FormData(form);const apiBase=String(fd.get('apiBase')||'').replace(/\/+$/,'');if(!apiBase)throw new Error('API Base URL is required');setApiBase(apiBase);const payload={species:fd.get('species'),cell_type:fd.get('cell_type'),gene_id:fd.get('gene_id'),perturbation:fd.get('perturbation'),strength:Number(fd.get('strength')),condition:fd.get('condition')};box.innerHTML=text('Submitting job…','正在提交任务…');const r=await fetch(`${apiBase}/api/predict`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text());const job=await r.json();box.innerHTML=`${text('Queued job','已排队任务')}: <b>${job.job_id}</b>`;await pollJob(apiBase,job.job_id)}catch(err){box.innerHTML=`<div class="notice compact"><b>${text('Prediction failed:','预测失败：')}</b> ${String(err.message||err)}</div>`}})}
function bind(){const q=$('#speciesSearch');if(q)q.addEventListener('input',()=>{const v=q.value.toLowerCase();$('#speciesGrid').innerHTML=speciesCards(catalog.species.filter(s=>[s.name,s.latin,s.family].join(' ').toLowerCase().includes(v))) });document.querySelectorAll('.panel img').forEach(img=>img.addEventListener('click',()=>{$('#lightbox img').src=img.src;$('#lightbox').classList.add('open')}));bindPredictor()}
function route(){const parts=(location.hash||'#/home').slice(2).split('/');let html;if(parts[0]==='home')html=home();else if(parts[0]==='species'&&parts[1])html=speciesDetail(parts[1]);else if(parts[0]==='species')html=species();else if(parts[0]==='analysis')html=analysisDetail(parts[1]);else if(parts[0]==='analyses')html=analyses();else if(parts[0]==='predictor')html=predictor();else if(parts[0]==='downloads')html=downloads();else if(parts[0]==='methods')html=methods();else html=notFound();app().innerHTML=html;window.scrollTo(0,0);bind()}
$('#lang').onclick=()=>{zh=!zh;route()};$('#lightbox button').onclick=()=>$('#lightbox').classList.remove('open');$('#lightbox').addEventListener('click',e=>{if(e.target.id==='lightbox')e.currentTarget.classList.remove('open')});
fetch('data/catalog.json').then(r=>r.json()).then(d=>{catalog=d;route()}).catch(e=>app().innerHTML=`<div class="loading">Failed to load catalog: ${e}</div>`);window.addEventListener('hashchange',route);
